export const CONSTANTS = {
    "days": [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday"
    ],
    "DaysInWeek":7,
    "Month":{
        1:{
            name:"January",
            daysCount:31
        },
        2:{
            name:"February",
            daysCount:28
        },
        3:{
            name:"March",
            daysCount:31
        },
        4:{
            name:"April",
            daysCount:30
        },
        5:{
            name:"May",
            daysCount:31
        },
        6:{
            name:"June",
            daysCount:30
        },
        7:{
            name:"July",
            daysCount:31
        },
        8:{
            name:"August",
            daysCount:31
        },
        9:{
            name:"September",
            daysCount:30
        },
        10:{
            name:"October",
            daysCount:31
        },
        11:{
            name:"November",
            daysCount:30
        },
        12:{
            name:"December",
            daysCount:31
        }
    },
    "daysShort": [
        "Sun",
        "Mon",
        "Tue",
        "Wed",
        "Thu",
        "Fri",
        "Sat"
    ],
    "months": [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ],
    "monthsShort": [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec"
    ]
}
