export const CONSTANTS = {
    "DaysMap": {
        1:"Sunday",
        2:"Monday",
        3:"Tuesday",
        4:"Wednesday",
        5:"Thursday",
        6:"Friday",
        7:"Saturday"
    },
    "DaysInWeek":6,
    "Month":{
        1:{
            name:"January",
            daysCount:31
        },
        2:{
            name:"February",
            daysCount:28
        },
        3:{
            name:"March",
            daysCount:31
        },
        4:{
            name:"April",
            daysCount:30
        },
        5:{
            name:"May",
            daysCount:31
        },
        6:{
            name:"June",
            daysCount:30
        },
        7:{
            name:"July",
            daysCount:31
        },
        8:{
            name:"August",
            daysCount:31
        },
        9:{
            name:"September",
            daysCount:30
        },
        10:{
            name:"October",
            daysCount:31
        },
        11:{
            name:"November",
            daysCount:30
        },
        12:{
            name:"December",
            daysCount:31
        }
    },
    "DaysMapShort": {
        1:"Sun",
        2:"Mon",
        3:"Tue",
        4:"Wed",
        5:"Thu",
        6:"Fri",
        7:"Sat"
    },
    "months": [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ],
    "monthsShort": [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec"
    ]
}
